//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoPanic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Veille_Desactive {
            get {
                return ((bool)(this["Veille_Desactive"]));
            }
            set {
                this["Veille_Desactive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InterfaceFilter_IP
        {
            get
            {
                return ((string)(this["InterfaceFilter_IP"]));
            }
            set
            {
                this["InterfaceFilter_IP"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int Port_Ecoute
        {
            get
            {
                return ((int)(this["Port_Ecoute"]));
            }
            set
            {
                this["Port_Ecoute"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1501")]
        public int Port_Envoi
        {
            get
            {
                return ((int)(this["Port_Envoi"]));
            }
            set
            {
                this["Port_Envoi"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TestPresence_Frequence {
            get {
                return ((int)(this["TestPresence_Frequence"]));
            }
            set {
                this["TestPresence_Frequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.255")]
        public string TestPresence_IP {
            get {
                return ((string)(this["TestPresence_IP"]));
            }
            set {
                this["TestPresence_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.255.255")]
        public string Alerte_IP {
            get {
                return ((string)(this["Alerte_IP"]));
            }
            set {
                this["Alerte_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Alerte_Touche {
            get {
                return ((int)(this["Alerte_Touche"]));
            }
            set {
                this["Alerte_Touche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alerte_Son {
            get {
                return ((bool)(this["Alerte_Son"]));
            }
            set {
                this["Alerte_Son"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALERTE AGRESSION")]
        public string Alerte_Titre {
            get {
                return ((string)(this["Alerte_Titre"]));
            }
            set {
                this["Alerte_Titre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%NOM%")]
        public string Alerte_Message {
            get {
                return ((string)(this["Alerte_Message"]));
            }
            set {
                this["Alerte_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Message reçu par vos collègues")]
        public string Alerte_Confirmation {
            get {
                return ((string)(this["Alerte_Confirmation"]));
            }
            set {
                this["Alerte_Confirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ce message apparait si vous avez un problème de communication ou qu\'aucun autre c" +
            "lient NoPanic n\'est présent sur le réseau.")]
        public string Erreur_Message {
            get {
                return ((string)(this["Erreur_Message"]));
            }
            set {
                this["Erreur_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirmation")]
        public string Quitter_Titre {
            get {
                return ((string)(this["Quitter_Titre"]));
            }
            set {
                this["Quitter_Titre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Est-vous sûr de vouloir quitter l\'application NoPanic ?")]
        public string Quitter_Message {
            get {
                return ((string)(this["Quitter_Message"]));
            }
            set {
                this["Quitter_Message"] = value;
            }
        }
    }
}
